### Definisco l'immagine temporanea di build basata su Go (pesante)
FROM golang:1.23 AS builder 

### Imposto la cartella di lavoro all'interno dell'immagine temporanea di build
WORKDIR /src/

### Copio il codice sorgente dell'applicazione Go nell'immagine temporanea di build
COPY . .

### Compilo l'applicazione Go nell'immagine temporanea di build
RUN go build -o /app/webapi ./cmd/webapi



### Definisco l'immagine finale basata su Debian slim (leggera)
FROM debian:bookworm-slim

### Espongo la porta su cui gira l'applicazione 
EXPOSE 3000

### Copio l'eseguibile dell'applicazione dall'immagine temporanea di build all'immagine finale
WORKDIR /app/
COPY --from=builder /app/webapi ./

### Quando il container parte, eseguo l'applicazione tramite questo comando
CMD ["/app/webapi"]