FROM golang:1.23 AS builder

### Copy Go code
WORKDIR /src/
COPY . .

### Build executables
RUN go build -o /app/webapi ./cmd/webapi

### Create final container
FROM debian:bookworm-slim

### Inform Docker about which port is used
EXPOSE 3000

### Copy the build executable from the builder image
WORKDIR /app/
COPY --from=builder /app/webapi ./

### Executable command
CMD ["/app/webapi"]